---
- hosts:
    - 127.0.0.1
  roles:
    - role: collivier.xtesting
      project: vsperfostack
      repo: 127.0.0.1
      dport: 5000
      gerrit:
      suites:
        - container: vsperfos
          tests:
            - phy2phy_tput
